# Generated by Django 3.1.4 on 2020-12-20 16:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='Esse/avatar.png', max_length=255, verbose_name='avatar'),
        ),
    ]
