# Generated by Django 3.1.4 on 2020-12-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_friendrequest_is_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_family',
            field=models.BooleanField(default=False),
        ),
    ]
