# Generated by Django 3.1.1 on 2020-09-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default='My Portfolio', verbose_name='Describe the contents or purpose for your this portfolio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Give your portfolio a name'),
        ),
    ]
