# Generated by Django 3.1.1 on 2020-10-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucket',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='bucket',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='bucket',
            old_name='updated_on',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='updated_date',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='bucket',
            name='slug',
            field=models.SlugField(max_length=100, unique_for_date='created'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(max_length=150, unique_for_date='created_on'),
        ),
    ]
