# Generated by Django 3.1.1 on 2020-10-04 09:48

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolios', '0003_auto_20201004_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='access_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=50), blank=True, help_text='Comma separated list of up to 8 email addresses that you want to share this bucket with. Not used on public buckets.', null=True, size=8),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(help_text='Give your portfolio a relevant name. ', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
    ]
