# Generated by Django 3.1.3 on 2020-11-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_auto_20201005_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(help_text='Give your portfolio a relevant name.', max_length=50),
        ),
    ]
