# Generated by Django 3.1.3 on 2020-12-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='album',
            name='unique_pvt_album',
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('title', 'profile'), name='unique_album'),
        ),
    ]
