# Generated by Django 3.1.4 on 2020-12-06 16:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_mediauploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediauploads',
            name='media',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
