# Generated by Django 3.1.4 on 2020-12-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('albums', '0004_auto_20201206_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaUploads',
            new_name='MediaUpload',
        ),
    ]
