# Generated by Django 3.1.4 on 2020-12-06 20:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_auto_20201206_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='media',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='auto'),
        ),
    ]
