# Generated by Django 3.1.4 on 2020-12-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_auto_20201207_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
