# Generated by Django 3.1.4 on 2020-12-08 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_auto_20201208_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album'),
        ),
    ]
