# Generated by Django 3.1.4 on 2020-12-09 09:08

import albums.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_friendrequest_is_relation'),
        ('albums', '0010_auto_20201208_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='media',
            field=models.FileField(upload_to=albums.models.album_media_dir),
        ),
    ]
