# Generated by Django 3.1.4 on 2020-12-09 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_auto_20201209_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='albums.album'),
        ),
    ]
