# Generated by Django 3.1.4 on 2020-12-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_auto_20201209_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='profile',
        ),
    ]
