# Generated by Django 3.1.4 on 2020-12-10 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_friendrequest_is_relation'),
        ('albums', '0013_remove_asset_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile'),
        ),
    ]
