# Generated by Django 3.1.4 on 2020-12-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_asset_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='description',
        ),
    ]
