# Generated by Django 3.1.4 on 2020-12-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0016_asset_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
