# Generated by Django 3.1.4 on 2020-12-13 16:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0017_auto_20201212_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='media',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='media'),
        ),
    ]
