# Generated by Django 3.1.4 on 2020-12-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0018_auto_20201213_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
