# Generated by Django 3.1.1 on 2020-09-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='Last Updated'),
        ),
    ]
